### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by chgresri** [EsriDevEvents/contributor-guides#5]
Can I ask for access to create a new repository for my 2 presentations at the European Dev Summit 2024 in Berlin?

The following session were presented:

•       ArcGIS Online: Web Mapping with Arcade Expressions
•       ArcGIS Field Maps: Using Arcade to Build Smarter Maps and Forms

Cheers,
Christian

**Comment by hhkaos** [comment]
Access granted! Thanks Christian! 😄
